2013-11-06 18:30:45,719 - esFrontLine - WARNING - processing problem
2013-11-06 18:30:45,721 - esFrontLine - ERROR - 'dict' object has no attribute 'host'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 59, in catch_all
    es.host + ":" + str(es.port) + "/" + path,
AttributeError: 'dict' object has no attribute 'host'
2013-11-06 18:30:45,835 - esFrontLine - WARNING - processing problem
2013-11-06 18:30:45,838 - esFrontLine - WARNING - processing problem
2013-11-06 18:30:45,851 - esFrontLine - WARNING - processing problem
2013-11-06 18:30:45,855 - esFrontLine - ERROR - 'dict' object has no attribute 'host'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 59, in catch_all
    es.host + ":" + str(es.port) + "/" + path,
AttributeError: 'dict' object has no attribute 'host'
2013-11-06 18:30:45,859 - esFrontLine - ERROR - 'dict' object has no attribute 'host'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 59, in catch_all
    es.host + ":" + str(es.port) + "/" + path,
AttributeError: 'dict' object has no attribute 'host'
2013-11-06 18:30:45,868 - esFrontLine - ERROR - 'dict' object has no attribute 'host'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 59, in catch_all
    es.host + ":" + str(es.port) + "/" + path,
AttributeError: 'dict' object has no attribute 'host'
2013-11-06 18:30:45,884 - esFrontLine - WARNING - processing problem
2013-11-06 18:30:45,904 - esFrontLine - ERROR - 'dict' object has no attribute 'host'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 59, in catch_all
    es.host + ":" + str(es.port) + "/" + path,
AttributeError: 'dict' object has no attribute 'host'
2013-11-06 18:30:46,092 - esFrontLine - WARNING - processing problem
2013-11-06 18:30:46,095 - esFrontLine - ERROR - 'dict' object has no attribute 'host'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 59, in catch_all
    es.host + ":" + str(es.port) + "/" + path,
AttributeError: 'dict' object has no attribute 'host'
2013-11-06 18:30:46,193 - esFrontLine - WARNING - processing problem
2013-11-06 18:30:46,194 - esFrontLine - WARNING - processing problem
2013-11-06 18:30:46,207 - esFrontLine - ERROR - 'dict' object has no attribute 'host'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 59, in catch_all
    es.host + ":" + str(es.port) + "/" + path,
AttributeError: 'dict' object has no attribute 'host'
2013-11-06 18:30:46,209 - esFrontLine - ERROR - 'dict' object has no attribute 'host'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 59, in catch_all
    es.host + ":" + str(es.port) + "/" + path,
AttributeError: 'dict' object has no attribute 'host'
2013-11-06 18:32:10,369 - esFrontLine - WARNING - processing problem
2013-11-06 18:32:10,371 - esFrontLine - ERROR - HTTPConnectionPool(host='elasticsearch8.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 63, in catch_all
    timeout=90
  File "C:\Python27\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='elasticsearch8.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
2013-11-06 18:32:10,378 - esFrontLine - WARNING - processing problem
2013-11-06 18:32:10,378 - esFrontLine - WARNING - processing problem
2013-11-06 18:32:10,427 - esFrontLine - WARNING - processing problem
2013-11-06 18:32:10,516 - esFrontLine - WARNING - processing problem
2013-11-06 18:32:13,124 - esFrontLine - ERROR - HTTPConnectionPool(host='elasticsearch4.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /org_chart/person/_mapping (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 63, in catch_all
    timeout=90
  File "C:\Python27\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='elasticsearch4.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /org_chart/person/_mapping (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
2013-11-06 18:32:13,127 - esFrontLine - ERROR - HTTPConnectionPool(host='elasticsearch5.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/bug_version/_mapping (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 63, in catch_all
    timeout=90
  File "C:\Python27\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='elasticsearch5.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/bug_version/_mapping (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
2013-11-06 18:32:13,187 - esFrontLine - ERROR - HTTPConnectionPool(host='elasticsearch8.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 63, in catch_all
    timeout=90
  File "C:\Python27\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='elasticsearch8.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
2013-11-06 18:32:13,190 - esFrontLine - ERROR - HTTPConnectionPool(host='elasticsearch5.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 63, in catch_all
    timeout=90
  File "C:\Python27\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='elasticsearch5.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
2013-11-06 18:32:34,512 - esFrontLine - WARNING - processing problem
2013-11-06 18:32:34,519 - esFrontLine - WARNING - processing problem
2013-11-06 18:32:34,529 - esFrontLine - WARNING - processing problem
2013-11-06 18:32:34,536 - esFrontLine - ERROR - HTTPConnectionPool(host='elasticsearch5.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /org_chart/person/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 63, in catch_all
    timeout=90
  File "C:\Python27\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='elasticsearch5.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /org_chart/person/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
2013-11-06 18:32:34,556 - esFrontLine - ERROR - HTTPConnectionPool(host='elasticsearch5.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/bug_version/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 63, in catch_all
    timeout=90
  File "C:\Python27\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='elasticsearch5.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/bug_version/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
2013-11-06 18:32:34,565 - esFrontLine - ERROR - HTTPConnectionPool(host='elasticsearch8.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/bug_version/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 63, in catch_all
    timeout=90
  File "C:\Python27\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='elasticsearch8.metrics.scl3.mozilla.com', port=9200): Max retries exceeded with url: /bugs/bug_version/_search (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)
2013-11-06 18:33:30,482 - esFrontLine - WARNING - processing problem
2013-11-06 18:33:30,484 - esFrontLine - ERROR - 'Logger' object has no attribute 'note'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 69, in catch_all
    logger.note("path: {path}, request bytes={request_content_length}, response bytes={response_content_length}".format(
AttributeError: 'Logger' object has no attribute 'note'
2013-11-06 18:33:30,586 - esFrontLine - WARNING - processing problem
2013-11-06 18:33:30,588 - esFrontLine - ERROR - 'Logger' object has no attribute 'note'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 69, in catch_all
    logger.note("path: {path}, request bytes={request_content_length}, response bytes={response_content_length}".format(
AttributeError: 'Logger' object has no attribute 'note'
2013-11-06 18:33:30,872 - esFrontLine - WARNING - processing problem
2013-11-06 18:33:30,875 - esFrontLine - ERROR - 'Logger' object has no attribute 'note'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 69, in catch_all
    logger.note("path: {path}, request bytes={request_content_length}, response bytes={response_content_length}".format(
AttributeError: 'Logger' object has no attribute 'note'
2013-11-06 18:33:31,052 - esFrontLine - WARNING - processing problem
2013-11-06 18:33:31,053 - esFrontLine - ERROR - 'Logger' object has no attribute 'note'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 69, in catch_all
    logger.note("path: {path}, request bytes={request_content_length}, response bytes={response_content_length}".format(
AttributeError: 'Logger' object has no attribute 'note'
2013-11-06 18:33:31,295 - esFrontLine - WARNING - processing problem
2013-11-06 18:33:31,295 - esFrontLine - WARNING - processing problem
2013-11-06 18:33:31,299 - esFrontLine - ERROR - 'Logger' object has no attribute 'note'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 69, in catch_all
    logger.note("path: {path}, request bytes={request_content_length}, response bytes={response_content_length}".format(
AttributeError: 'Logger' object has no attribute 'note'
2013-11-06 18:33:31,301 - esFrontLine - ERROR - 'Logger' object has no attribute 'note'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 69, in catch_all
    logger.note("path: {path}, request bytes={request_content_length}, response bytes={response_content_length}".format(
AttributeError: 'Logger' object has no attribute 'note'
2013-11-06 18:33:32,135 - esFrontLine - WARNING - processing problem
2013-11-06 18:33:32,138 - esFrontLine - ERROR - 'Logger' object has no attribute 'note'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 69, in catch_all
    logger.note("path: {path}, request bytes={request_content_length}, response bytes={response_content_length}".format(
AttributeError: 'Logger' object has no attribute 'note'
2013-11-06 18:33:32,219 - esFrontLine - WARNING - processing problem
2013-11-06 18:33:32,223 - esFrontLine - ERROR - 'Logger' object has no attribute 'note'
Traceback (most recent call last):
  File "C:/Users/klahnakoski/git/esFrontLine/esFrontLine/app.py", line 69, in catch_all
    logger.note("path: {path}, request bytes={request_content_length}, response bytes={response_content_length}".format(
AttributeError: 'Logger' object has no attribute 'note'
2013-11-06 18:34:51,342 - esFrontLine - DEBUG - path: org_chart/person/_mapping, request bytes=0, response bytes=143
2013-11-06 18:34:51,451 - esFrontLine - DEBUG - path: bugs/bug_version/_mapping, request bytes=0, response bytes=4929
2013-11-06 18:34:51,650 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=550
2013-11-06 18:34:51,750 - esFrontLine - DEBUG - path: org_chart/person/_search, request bytes=1353, response bytes=25844
2013-11-06 18:34:51,757 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=550
2013-11-06 18:34:51,875 - esFrontLine - DEBUG - path: bugs/_search, request bytes=480, response bytes=1124
2013-11-06 18:34:53,125 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=258, response bytes=282
2013-11-06 18:34:53,247 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=574, response bytes=10427
2013-11-06 18:35:09,164 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=708, response bytes=317858
2013-11-06 18:35:10,023 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=1214, response bytes=459
2013-11-06 18:35:50,032 - esFrontLine - DEBUG - path: org_chart/person/_mapping, request bytes=0, response bytes=143
2013-11-06 18:35:50,043 - esFrontLine - DEBUG - path: bugs/bug_version/_mapping, request bytes=0, response bytes=4929
2013-11-06 18:35:50,460 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=550
2013-11-06 18:35:50,490 - esFrontLine - DEBUG - path: org_chart/person/_search, request bytes=1353, response bytes=25847
2013-11-06 18:35:50,700 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=551
2013-11-06 18:35:50,809 - esFrontLine - DEBUG - path: bugs/_search, request bytes=480, response bytes=1122
2013-11-06 18:35:51,509 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=574, response bytes=10429
2013-11-06 18:35:51,641 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=258, response bytes=282
2013-11-06 18:36:18,509 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=708, response bytes=317848
2013-11-06 18:36:19,234 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=1214, response bytes=459
2013-11-06 18:37:07,921 - esFrontLine - DEBUG - path: org_chart/person/_mapping, request bytes=0, response bytes=143
2013-11-06 18:37:07,966 - esFrontLine - DEBUG - path: bugs/bug_version/_mapping, request bytes=0, response bytes=4929
2013-11-06 18:37:08,276 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=550
2013-11-06 18:37:08,278 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=550
2013-11-06 18:37:08,400 - esFrontLine - DEBUG - path: bugs/_search, request bytes=480, response bytes=1124
2013-11-06 18:37:10,973 - esFrontLine - DEBUG - path: org_chart/person/_search, request bytes=1353, response bytes=25846
2013-11-06 18:37:11,311 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=574, response bytes=10426
2013-11-06 18:37:12,223 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=258, response bytes=281
2013-11-06 18:37:33,994 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=708, response bytes=317851
2013-11-06 18:37:34,657 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=1214, response bytes=460
2013-11-06 18:37:40,335 - esFrontLine - DEBUG - path: bugs/bug_version/_mapping, request bytes=0, response bytes=4929
2013-11-06 18:37:40,395 - esFrontLine - DEBUG - path: org_chart/person/_mapping, request bytes=0, response bytes=143
2013-11-06 18:37:40,720 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=550
2013-11-06 18:37:41,786 - esFrontLine - DEBUG - path: org_chart/person/_search, request bytes=1353, response bytes=25844
2013-11-06 18:37:41,911 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=550
2013-11-06 18:37:42,052 - esFrontLine - DEBUG - path: bugs/_search, request bytes=480, response bytes=1121
2013-11-06 18:37:42,904 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=258, response bytes=283
2013-11-06 18:37:43,105 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=574, response bytes=10429
2013-11-06 18:38:08,002 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=549
2013-11-06 18:38:08,729 - esFrontLine - DEBUG - path: org_chart/person/_mapping, request bytes=0, response bytes=143
2013-11-06 18:38:08,736 - esFrontLine - DEBUG - path: bugs/bug_version/_mapping, request bytes=0, response bytes=4929
2013-11-06 18:38:09,299 - esFrontLine - DEBUG - path: org_chart/person/_search, request bytes=1353, response bytes=25846
2013-11-06 18:38:09,463 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=549
2013-11-06 18:38:09,651 - esFrontLine - DEBUG - path: bugs/_search, request bytes=480, response bytes=1123
2013-11-06 18:38:10,642 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=258, response bytes=282
2013-11-06 18:38:10,953 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=574, response bytes=10427
2013-11-06 18:38:12,779 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=1214, response bytes=459
2013-11-06 18:38:13,026 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=708, response bytes=317848
2013-11-06 18:38:31,868 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=708, response bytes=317848
2013-11-06 18:38:33,217 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=1214, response bytes=458
2013-11-06 18:38:39,674 - esFrontLine - DEBUG - path: org_chart/person/_mapping, request bytes=0, response bytes=143
2013-11-06 18:38:39,680 - esFrontLine - DEBUG - path: bugs/bug_version/_mapping, request bytes=0, response bytes=4929
2013-11-06 18:38:39,875 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=550
2013-11-06 18:38:44,707 - esFrontLine - DEBUG - path: bugs/_search, request bytes=4409, response bytes=550
2013-11-06 18:38:44,858 - esFrontLine - DEBUG - path: org_chart/person/_search, request bytes=1353, response bytes=25847
2013-11-06 18:38:44,867 - esFrontLine - DEBUG - path: bugs/_search, request bytes=480, response bytes=1122
2013-11-06 18:38:45,006 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=574, response bytes=10428
2013-11-06 18:38:45,802 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=258, response bytes=282
2013-11-06 18:39:07,051 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=708, response bytes=317849
2013-11-06 18:39:07,973 - esFrontLine - DEBUG - path: bugs/bug_version/_search, request bytes=1214, response bytes=459
